# Generated by Django 5.0.2 on 2025-08-25 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('F', 'Fijo'), ('V', 'Variable')], default='F', max_length=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.unidadnegocio')),
            ],
        ),
        migrations.CreateModel(
            name='LetraTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
                ('valor', models.CharField(max_length=2)),
                ('modelo_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letras', to='programacion_models.modeloturno')),
            ],
            options={
                'unique_together': {('modelo_turno', 'fila', 'columna')},
            },
        ),
    ]
