# Generated by Django 5.0.2 on 2025-06-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTurno5x3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_turno', to='empresas.centrooperativo')),
            ],
            options={
                'verbose_name': 'Modelo Turno 5x3',
                'verbose_name_plural': 'Modelos Turno 5x3',
                'permissions': [('ver_modelo', 'Puede ver modelo de turnos'), ('generar_programacion', 'Puede generar programación')],
            },
        ),
        migrations.CreateModel(
            name='CargoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.cargo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion_models.modeloturno5x3')),
            ],
            options={
                'verbose_name': 'Cargo Requerido',
                'verbose_name_plural': 'Cargos Requeridos',
                'unique_together': {('modelo', 'cargo')},
            },
        ),
    ]
