# Generated by Django 5.0.2 on 2025-06-24 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_patron', models.CharField(choices=[('5x3', '5x3 (4 filas x 16 columnas)'), ('3x3', '3x3 (3 filas x 3 columnas)')], help_text='Selecciona el tamaño y tipo de patrón base', max_length=10)),
                ('matriz', models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('F', 'Fijo'), ('V', 'Variable')], default='F', max_length=1)),
                ('matriz_letras', models.JSONField(blank=True, help_text='Matriz personalizada para este modelo de turno, basada en el patrón base.', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.centrooperativo')),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.unidadnegocio')),
                ('patron_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_models.patronbase')),
            ],
        ),
    ]
