# Generated by Django 5.0.2 on 2025-07-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronbase',
            name='tipo_patron',
            field=models.CharField(choices=[('5x3', '5x3 (4 filas x 16 columnas)'), ('3x3', '3x3 (3 filas x 6 columnas)')], help_text='Selecciona el tamaño y tipo de patrón base', max_length=10),
        ),
    ]
