# Generated by Django 5.0.2 on 2025-06-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_models', '0001_initial_modelo_turno5x3'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloturno5x3',
            name='tipo_turno',
            field=models.CharField(choices=[('F', 'Fijo'), ('V', 'Variable')], default='F', help_text='Indica si el modelo es fijo o variable', max_length=1),
        ),
    ]
