# Generated by Django 5.0.2 on 2025-07-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_models', '0002_alter_patronbase_tipo_patron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloturno',
            name='patron_base',
        ),
        migrations.RemoveField(
            model_name='modeloturno',
            name='centro_operativo',
        ),
        migrations.RemoveField(
            model_name='modeloturno',
            name='matriz_letras',
        ),
        migrations.CreateModel(
            name='LetraTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
                ('valor', models.CharField(max_length=2)),
                ('modelo_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letras', to='programacion_models.modeloturno')),
            ],
            options={
                'unique_together': {('modelo_turno', 'fila', 'columna')},
            },
        ),
        migrations.DeleteModel(
            name='PatronBase',
        ),
    ]
