# Generated by Django 5.0.2 on 2025-06-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='documento',
            field=models.CharField(error_messages={'unique': 'Ya existe un tercero con este documento.'}, max_length=20, unique=True),
        ),
    ]
