# Generated by Django 5.0.2 on 2025-08-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoturno',
            name='segmentos_horas',
        ),
    ]
