# Generated by Django 5.0.2 on 2025-07-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_centrooperativo_promesa_valor'),
        ('usuarios', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='cargo',
        ),
        migrations.AddField(
            model_name='tercero',
            name='cargo_predefinido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terceros', to='empresas.cargopredefinido'),
        ),
    ]
