# Generated by Django 5.0.2 on 2025-07-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_cargo_centro_operativo'),
        ('usuarios', '0003_remove_tercero_cargo_tercero_cargo_predefinido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo_predefinido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.cargopredefinido'),
        ),
    ]
