# Generated by Django 5.0.2 on 2025-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_cargo_usuario_cargo_predefinido'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoturno',
            name='descripcion_novedad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='codigoturno',
            name='segmentos_horas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='codigoturno',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('D', 'Descanso'), ('F', 'Festivo'), ('FO', 'Festivo Ordinario'), ('ND', 'No Devengado'), ('E', 'Especial')], default='N', max_length=2),
        ),
    ]
