# Generated by Django 5.0.2 on 2025-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_codigoturno_descripcion_novedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoturno',
            name='duracion_total',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duración total del turno en horas (se calcula automáticamente)', max_digits=4, null=True, verbose_name='Duración Total (horas)'),
        ),
    ]
