# Generated by Django 5.0.2 on 2025-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('letra_turno', models.CharField(max_length=2)),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('tipo_accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAR', 'Consultar')], max_length=20, verbose_name='Tipo de Acción')),
                ('modulo', models.CharField(choices=[('programacion', 'Programación'), ('turnos', 'Turnos'), ('empleados', 'Empleados'), ('modelos', 'Modelos de Turno'), ('usuarios', 'Usuarios')], max_length=20, verbose_name='Módulo')),
                ('modelo_afectado', models.CharField(max_length=50, verbose_name='Modelo Afectado')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('valores_anteriores', models.JSONField(blank=True, null=True, verbose_name='Valores Anteriores')),
                ('valores_nuevos', models.JSONField(blank=True, null=True, verbose_name='Valores Nuevos')),
                ('campos_modificados', models.JSONField(blank=True, null=True, verbose_name='Campos Modificados')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
