# Generated by Django 5.0.2 on 2025-07-09 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_centrooperativo_promesa_valor'),
        ('programacion_models', '0003_remove_modeloturno_patron_base_and_more'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.centrooperativo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modelo_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_models.modeloturno')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('letra_turno', models.CharField(max_length=2)),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tercero')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='programacion_turnos.programacionhorario')),
            ],
        ),
    ]
