# Generated by Django 5.0.2 on 2025-07-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionturno',
            name='columna',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionturno',
            name='fila',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
