# Generated by Django 5.0.2 on 2025-07-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionturno',
            name='indice_letra',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
