# Generated by Django 5.0.2 on 2025-08-25 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('programacion_models', '0001_initial'),
        ('programacion_turnos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionturno',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tercero'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='programacionhorario',
            name='cargo_predefinido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.cargopredefinido'),
        ),
        migrations.AddField(
            model_name='programacionhorario',
            name='centro_operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.centrooperativo'),
        ),
        migrations.AddField(
            model_name='programacionhorario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programacionhorario',
            name='modelo_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_models.modeloturno'),
        ),
        migrations.AddField(
            model_name='asignacionturno',
            name='programacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='programacion_turnos.programacionhorario'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario', 'fecha_hora'], name='programacio_usuario_fa66fe_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['tipo_accion', 'fecha_hora'], name='programacio_tipo_ac_c884f5_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['modulo', 'fecha_hora'], name='programacio_modulo_66b2eb_idx'),
        ),
    ]
