# Generated by Django 5.0.2 on 2025-07-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_turnos', '0002_asignacionturno_indice_letra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionturno',
            name='indice_letra',
        ),
    ]
