# Generated by Django 5.0.2 on 2025-08-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_turnos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionhorario',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre de la programación'),
            preserve_default=False,
        ),
    ]
