# Generated by Django 5.0.2 on 2025-07-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_turnos', '0003_remove_indice_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionhorario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
