# Generated by Django 5.0.2 on 2025-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_turnos', '0003_programacionhorario_nombre'),
        ('usuarios', '0002_remove_codigoturno_segmentos_horas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionturno',
            options={'verbose_name': 'Asignación de Turno', 'verbose_name_plural': 'Asignaciones de Turno'},
        ),
        migrations.AlterField(
            model_name='asignacionturno',
            name='letra_turno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionturno',
            unique_together={('programacion', 'tercero', 'dia')},
        ),
    ]
