# Generated by Django 5.0.2 on 2025-07-29 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_turnos', '0004_programacionhorario_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('tipo_accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAR', 'Consultar')], max_length=20, verbose_name='Tipo de Acción')),
                ('modulo', models.CharField(choices=[('programacion', 'Programación'), ('turnos', 'Turnos'), ('empleados', 'Empleados'), ('modelos', 'Modelos de Turno'), ('usuarios', 'Usuarios')], max_length=20, verbose_name='Módulo')),
                ('modelo_afectado', models.CharField(max_length=50, verbose_name='Modelo Afectado')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('valores_anteriores', models.JSONField(blank=True, null=True, verbose_name='Valores Anteriores')),
                ('valores_nuevos', models.JSONField(blank=True, null=True, verbose_name='Valores Nuevos')),
                ('campos_modificados', models.JSONField(blank=True, null=True, verbose_name='Campos Modificados')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'fecha_hora'], name='programacio_usuario_fa66fe_idx'), models.Index(fields=['tipo_accion', 'fecha_hora'], name='programacio_tipo_ac_c884f5_idx'), models.Index(fields=['modulo', 'fecha_hora'], name='programacio_modulo_66b2eb_idx')],
            },
        ),
    ]
