# Generated by Django 5.0.2 on 2025-07-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_turnos', '0005_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
    ]
