# Generated by Django 5.0.2 on 2025-08-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_delete_cargo'),
        ('programacion_turnos', '0006_alter_bitacora_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionhorario',
            name='cargo_predefinido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.cargopredefinido'),
            preserve_default=False,
        ),
    ]
