# Generated by Django 5.0.2 on 2025-06-16 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionTurnos',
            fields=[
                ('id_programacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'En Proceso'), (3, 'Finalizado')], default=1)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='empresas.centrooperativo')),
            ],
            options={
                'verbose_name': 'Programación de Turnos',
                'verbose_name_plural': 'Programaciones de Turnos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
