# Generated by Django 5.0.2 on 2025-06-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTerceroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignación de Tercero',
                'verbose_name_plural': 'Asignaciones de Terceros',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CargoPredefinido',
            fields=[
                ('id_cargo_predefinido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción general de las funciones del cargo')),
                ('nivel', models.CharField(choices=[('ALTO', 'Nivel Alto'), ('MEDIO', 'Nivel Medio'), ('OPERATIVO', 'Nivel Operativo')], default='OPERATIVO', help_text='Nivel jerárquico del cargo', max_length=20)),
                ('area', models.CharField(choices=[('ADMINISTRATIVA', 'Área Administrativa'), ('OPERATIVA', 'Área Operativa'), ('COMERCIAL', 'Área Comercial'), ('TECNICA', 'Área Técnica'), ('OTROS', 'Otras Áreas')], default='OTROS', help_text='Área funcional del cargo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado_cargo', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cargo Predefinido',
                'verbose_name_plural': 'Cargos Predefinidos',
                'ordering': ['area', 'nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CentroOperativo',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro Operativo',
                'verbose_name_plural': 'Centros Operativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id_uen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado_uen', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Unidad de Negocio',
                'verbose_name_plural': 'Unidades de Negocio',
            },
        ),
    ]
