# Generated by Django 5.0.2 on 2025-06-20 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionterceroempresa',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tercero'),
        ),
        migrations.AlterUniqueTogether(
            name='cargopredefinido',
            unique_together={('nombre', 'nivel')},
        ),
        migrations.AddField(
            model_name='centrooperativo',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_operativos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='centro_operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='empresas.centrooperativo'),
        ),
        migrations.AddField(
            model_name='asignacionterceroempresa',
            name='centro_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.centrooperativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='terceros',
            field=models.ManyToManyField(related_name='empresas', through='empresas.AsignacionTerceroEmpresa', to='usuarios.tercero'),
        ),
        migrations.AddField(
            model_name='asignacionterceroempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_empresa_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centrooperativo',
            name='proyectos',
            field=models.ManyToManyField(related_name='centros_operativos', to='empresas.proyecto', verbose_name='Proyectos'),
        ),
        migrations.AddField(
            model_name='unidadnegocio',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='unidades_negocio', to='empresas.empresa', verbose_name='Empresas'),
        ),
        migrations.AddField(
            model_name='unidadnegocio',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionterceroempresa',
            unique_together={('tercero', 'empresa')},
        ),
    ]
