# Generated by Django 5.0.2 on 2025-08-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrooperativo',
            name='promesa_valor',
            field=models.IntegerField(blank=True, help_text='Valor informativo de promesa de valor para el centro operativo.', null=True, verbose_name='PV (Cantidad de Casetas)'),
        ),
    ]
