# Generated by Django 5.0.2 on 2025-07-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_cargo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrooperativo',
            name='promesa_valor',
            field=models.IntegerField(blank=True, help_text='Valor informativo de promesa de valor para el centro operativo.', null=True, verbose_name='Promesa de Valor (Pv)'),
        ),
    ]
