# Generated by Django 5.0.2 on 2025-07-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_centrooperativo_promesa_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='centro_operativo',
        ),
    ]
