# Generated by Django 5.0.2 on 2025-07-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_cargo_centro_operativo'),
        ('usuarios', '0004_remove_usuario_cargo_usuario_cargo_predefinido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
